### ISSUE TITLE
NHS CCG ID now in postcodes.io

### ISSUE THREAD

**Issue by willwade** [stephenkeable/ccg-lookup#1]
Just a FYI.. Postcodes.io now supports CCG ID's (i.e the shortcode):

https://github.com/ideal-postcodes/postcodes.io/commit/a22af64a57445dcba626ca87c59e4540733a347f

<img width="763" alt="Screenshot 2020-01-08 at 20 38 10" src="https://user-images.githubusercontent.com/229352/72015844-6ddf0800-325a-11ea-9bb0-95d3e1805cf4.png">

With all the ccg changes that are happening in April this might make things a bit easier.. 

Also - this looks like more up-to-date info on the CCG titles etc (that NHSPD link in the readme is an absolute nightmare of a dump of data):

https://digital.nhs.uk/services/organisation-data-service/data-downloads/other-nhs-organisations

(Ref https://github.com/AceCentre/nhs-service-finder/issues/17 )

**Comment by stephenkeable** [comment]
Sorry it took so long to respond, now fetching the code from postcodes.io as your suggestion.
Also returning ICB instead of CCG as per the API
