### ISSUE TITLE
NHS code missing for some postcodes?

### ISSUE THREAD

**Issue by NickHalfhead** [stephenkeable/ccg-lookup#2]
Hi,
I was expecting to see the NHS [CCG] code of "92G" for postcode SN7 7SS?
Thanks,
N.

**Comment by stephenkeable** [comment]
Well looks like over 2 years later that postcode returns the correct code :)
Sorry it took so long to reply.
As a side note for others, postcodes can be added or changed by Royal Mail and those updates might not be reflected in the data for some time, as the source open data used by postcodes.io might have a slower update frequency than the Royal Mail postcode changes.
